import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

// Generated by scripts/import-listings.ts — do not edit src/content/listings/*.json by hand.
const nullableBool = z.boolean().nullable();
const nullableNum = z.number().nullable();

const listings = defineCollection({
  loader: glob({ pattern: '*.json', base: './src/content/listings' }),
  schema: ({ image }) =>
    z.object({
      ref: z.string().regex(/^B\d{3}$/),
      slugSq: z.string(),
      slugEn: z.string(),
      postedAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
      instagramUrl: z.url(),
      deal: z.enum(['sale', 'rent']),
      type: z.enum(['apartment', 'duplex', 'penthouse', 'house', 'land', 'commercial', 'office', 'warehouse', 'building']),
      multipleUnits: z.boolean(),
      titleSq: z.string(),
      titleEn: z.string(),
      city: z.string().nullable(),
      cityEn: z.string().nullable(),
      neighbourhood: z.string().nullable(),
      neighbourhoodLoc: z.string().nullable(),
      street: z.string().nullable(),
      complex: z.string().nullable(),
      landmark: z.string().nullable(),
      landmarkEn: z.string().nullable(),
      country: z.enum(['XK', 'ME', 'AL']).nullable(),
      developer: z.string().nullable(),
      isNewBuild: nullableBool,
      completion: z.string().nullable(),
      completionEn: z.string().nullable(),
      areaNet: nullableNum,
      areaApprox: z.boolean(),
      areaTerrace: nullableNum,
      plotAres: nullableNum,
      floor: nullableNum,
      floorTo: nullableNum,
      totalFloors: nullableNum,
      orientation: z.string().nullable(),
      bedrooms: nullableNum,
      bathrooms: nullableNum,
      wc: nullableNum,
      livingWithKitchen: nullableBool,
      storage: nullableBool,
      balcony: nullableBool,
      features: z.array(z.string()),
      legal: z.object({
        ownershipCertificate: nullableBool,
        notaryContract: nullableBool,
        contractViaLawyer: nullableBool,
        inLegalisation: nullableBool,
        contractWithDeveloper: nullableBool,
      }),
      price: nullableNum,
      pricePerM2: nullableNum,
      pricePerAre: nullableNum,
      priceOnRequest: z.boolean(),
      rentMonthly: nullableNum,
      deposit: nullableNum,
      minContractMonths: nullableNum,
      extras: z.object({
        financing: z.string().nullable(),
        installments: nullableBool,
        tradeIn: z.string().nullable(),
        tradeInEn: z.string().nullable(),
        tenanted: nullableBool,
        rentalIncome: nullableNum,
        garageOptional: nullableBool,
      }),
      aiVisualisation: z.boolean(),
      aiDisclaimerSq: z.string().nullable(),
      aiDisclaimerEn: z.string().nullable(),
      status: z.enum(['unconfirmed', 'available', 'reserved', 'sold', 'rented']),
      hidden: z.boolean(),
      descriptionSq: z.array(z.string()).min(1),
      descriptionEn: z.array(z.string()).nullable(),
      descriptionEnIsTranslation: z.boolean(),
      extraCaptions: z.array(z.object({ url: z.string(), sq: z.array(z.string()), en: z.array(z.string()).nullable() })),
      images: z
        .array(
          z.object({
            src: image(),
            file: z.string(),
            width: z.number(),
            height: z.number(),
            kind: z.string(),
            overlay: z.enum(['none', 'brand', 'text']).nullable(),
            hasTextOverlay: nullableBool,
            altSq: z.string(),
            altEn: z.string(),
          }),
        )
        .min(1),
      coverIndex: z.number().int().min(0),
      provenance: z.any(),
    }),
});

export const collections = { listings };
